#!/bin/bash
set -e

INSTALL_DIR="/home/redmine/redmine"
CONFIG_DIR="${INSTALL_DIR}/config"
DATA_DIR="/home/redmine/data"
LOG_DIR="/var/log/redmine"
SSL_CERTIFICATES_DIR="${DATA_DIR}/certs"

SETUP_DIR="/app/setup"
SYSCONF_TEMPLATES_DIR="${SETUP_DIR}/config"
USERCONF_TEMPLATES_DIR="${DATA_DIR}/config"

DB_HOST=${DB_HOST:-}
DB_PORT=${DB_PORT:-}
DB_NAME=${DB_NAME:-redmine}
DB_USER=${DB_USER:-redmine}
DB_PASS=${DB_PASS:-}
DB_POOL=${DB_POOL:-5}
DB_TYPE=${DB_TYPE:-}

SMTP_METHOD=${SMTP_METHOD:-smtp}
SMTP_DOMAIN=${SMTP_DOMAIN:-www.gmail.com}
SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}
SMTP_OPENSSL_VERIFY_MODE=${SMTP_OPENSSL_VERIFY_MODE:-}
SMTP_STARTTLS=${SMTP_STARTTLS:-true}

if [ -n "${SMTP_USER}" ]; then
  SMTP_ENABLED=${SMTP_ENABLED:-true}
  SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION:-:login}
fi

SMTP_ENABLED=${SMTP_ENABLED:-false}

REDMINE_PORT=${REDMINE_PORT:-}
REDMINE_HTTPS=${REDMINE_HTTPS:-false}
REDMINE_RELATIVE_URL_ROOT=${REDMINE_RELATIVE_URL_ROOT:-}
REDMINE_FETCH_COMMITS=${REDMINE_FETCH_COMMITS:-disable}

REDMINE_HTTPS_HSTS_ENABLED=${REDMINE_HTTPS_HSTS_ENABLED:-true}
REDMINE_HTTPS_HSTS_MAXAGE=${REDMINE_HTTPS_HSTS_MAXAGE:-31536000}

NGINX_WORKERS=${NGINX_WORKERS:-1}
NGINX_MAX_UPLOAD_SIZE=${NGINX_MAX_UPLOAD_SIZE:-20m}

SSL_CERTIFICATE_PATH=${SSL_CERTIFICATE_PATH:-${SSL_CERTIFICATES_DIR}/redmine.crt}
SSL_KEY_PATH=${SSL_KEY_PATH:-${SSL_CERTIFICATES_DIR}/redmine.key}
SSL_DHPARAM_PATH=${SSL_DHPARAM_PATH:-${SSL_CERTIFICATES_DIR}/dhparam.pem}
SSL_VERIFY_CLIENT=${SSL_VERIFY_CLIENT:-off}

UNICORN_WORKERS=${UNICORN_WORKERS:-2}
UNICORN_TIMEOUT=${UNICORN_TIMEOUT:-60}

# is a postgresql database linked?
# requires that the postgresql containers have exposed
# port 5432
if [ -n "${POSTGRESQL_PORT_5432_TCP_ADDR}" ]; then
  DB_TYPE=postgres
  DB_HOST=${DB_HOST:-${POSTGRESQL_PORT_5432_TCP_ADDR}}
  DB_PORT=${DB_PORT:-${POSTGRESQL_PORT_5432_TCP_PORT}}
fi

if [ -z "${DB_HOST}" ]; then
  echo "ERROR: "
  echo "  Please configure the database connection."
  echo "  Refer http://git.io/JkE-cw for more information."
  echo "  Cannot continue without a database. Aborting..."
  exit 1
fi

case "${REDMINE_HTTPS}" in
  true)
    REDMINE_PORT=${REDMINE_PORT:-443}
    NGINX_X_FORWARDED_PROTO=${NGINX_X_FORWARDED_PROTO:-https}
    ;;
  *)
    REDMINE_PORT=${REDMINE_PORT:-80}
    NGINX_X_FORWARDED_PROTO=${NGINX_X_FORWARDED_PROTO:-\$scheme}
    ;;
esac

# generate ssh keys
echo "Generating SSH keys..."
mkdir -p ${DATA_DIR}/dotfiles/.ssh/
chown -R redmine:redmine ${DATA_DIR}/dotfiles/.ssh/
rm -rf ${DATA_DIR}/dotfiles/.ssh/id_rsa ${DATA_DIR}/dotfiles/.ssh/id_rsa.pub
sudo -u redmine -H ssh-keygen -t rsa -N "" -f ${DATA_DIR}/dotfiles/.ssh/id_rsa

# ---------------------------- Gitolite ----------------------------

# If /repositories mounted and soft link does not exist, \
# create it and set proper permission
if [ -d /repositories -a ! -h /home/git/repositories ]; then
  echo "Creating soft link to repositories directory"
  sudo -u git -H rm -rf /home/git/repositories && ln -s /repositories /home/git/repositories
  chown -R git:git /home/git/repositories /repositories
fi

if [ ! -d /home/git/.gitolite ] ; then
  # gitolite needs to be set up
  # if [ -h ${DATA_DIR}/dotfiles/.ssh/redmine_gitolite_admin_id_rsa.pub ]; then
    echo -e "\n\t\tInitializing gitolite to work with redmine...\n"

    # create keys symlinks for gitolite and add gitolite host to known_hosts
    pushd ${DATA_DIR}/dotfiles/.ssh/
    sudo -u redmine -H ln -s id_rsa redmine_gitolite_admin_id_rsa
    sudo -u redmine -H ln -s id_rsa.pub redmine_gitolite_admin_id_rsa.pub
    # sudo -u redmine -H ssh-keyscan -H localhost >> known_hosts
    sudo -u redmine -H echo -e "Host localhost\n  NoHostAuthenticationForLocalhost yes" >> config
    popd

    # make sure the ssh keys have the right permissions
    chmod -R 400 ${DATA_DIR}/dotfiles/.ssh/*
    chmod -R 750 ${DATA_DIR}/dotfiles/.ssh/*.pub

    sudo -u git -H gitolite setup -pk ${DATA_DIR}/dotfiles/.ssh/redmine_gitolite_admin_id_rsa.pub

    # Apply config customizations. We need to do this now,
    # because w/o the right config, the compile may fail.
    rcfile=/home/git/.gitolite.rc
    sed -i "s/GIT_CONFIG_KEYS.*=>.*''/GIT_CONFIG_KEYS => \"${GIT_CONFIG_KEYS}\"/g" $rcfile
    if [ -n "$LOCAL_CODE" ]; then
       sed -i "s|# LOCAL_CODE.*=>.*$|LOCAL_CODE => \"${LOCAL_CODE}\",|" $rcfile
    fi
  # else
  #   # If no SSH key is given, we instead try to support
  #   # bootstrapping from an existing gitolite-admin.

  #   # Unfortunately, gitolite setup will add a new
  #   # commit to an existing gitolite-admin dir that
  #   # resets everything. We avoid this by renaming it first.
  #   if [ -d ./repositories/gitolite-admin.git ]; then
  #      mv ./repositories/gitolite-admin.git ./repositories/gitolite-admin.git-tmp
  #   fi

  #   # First, setup gitolite without an ssh key.
  #   # My understanding is that this is essentially a noop,
  #   # auth-wise. setup will still generate the .gitolite
  #   # folder and .gitolite.rc files.
  #   echo "Initializing gitolite without authorizing a key for accessing the admin repo"
  #   sudo -u git -H gitolite setup -a dummy

  #   # Remove the gitolite-admin repo generated by setup.
  #   if [ -d ./repositories/gitolite-admin.git-tmp ]; then
  #      rm -rf ./repositories/gitolite-admin.git
  #      mv ./repositories/gitolite-admin.git-tmp ./repositories/gitolite-admin.git
  #   fi

  #   # Apply config customizations. We need to do this now,
  #   # because w/o the right config, the compile may fail.
  #   rcfile=/home/git/.gitolite.rc
  #   sed -i "s/GIT_CONFIG_KEYS.*=>.*''/GIT_CONFIG_KEYS => \"${GIT_CONFIG_KEYS}\"/g" $rcfile
  #   if [ -n "$LOCAL_CODE" ]; then
  #      sed -i "s|# LOCAL_CODE.*=>.*$|LOCAL_CODE => \"${LOCAL_CODE}\",|" $rcfile
  #   fi

  #   # We will need to update authorized_keys based on
  #   # the gitolite-admin repo. The way to do this is by
  #   # triggering the post-update hook of the gitolite-admin
  #   # repo (thanks to sitaram for the solution):
  #   sudo -u git -H cd /home/git/repositories/gitolite-admin.git && GL_LIBDIR=$(gitolite query-rc GL_LIBDIR) PATH=$PATH:/home/git/bin hooks/post-update refs/heads/master
  # fi
else
  # Resync on every restart
  sudo -u git -H gitolite setup
fi

# ---------------------------- End Gitolite ----------------------------

# create the .subversion directory
mkdir -p ${DATA_DIR}/dotfiles/.subversion/

# fix ownership of the ${DATA_DIR}dotfiles/ directory
chown -R redmine:redmine ${DATA_DIR}/dotfiles

# fix ownership of ${DATA_DIR}/tmp/
mkdir -p ${DATA_DIR}/tmp/
chown -R redmine:redmine ${DATA_DIR}/tmp/

# populate ${LOG_DIR}
mkdir -m 0755 -p ${LOG_DIR}/supervisor  && chown -R root:root ${LOG_DIR}/supervisor
mkdir -m 0755 -p ${LOG_DIR}/nginx       && chown -R redmine:redmine ${LOG_DIR}/nginx
mkdir -m 0755 -p ${LOG_DIR}/redmine     && chown -R redmine:redmine ${LOG_DIR}/redmine

# fix permission and ownership of ${DATA_DIR}
chmod 755 ${DATA_DIR}
chown redmine:redmine ${DATA_DIR}

# set executable flags on ${DATA_DIR} (needed if mounted from a data-only
# container using --volumes-from)
chmod +x ${DATA_DIR}

cd ${INSTALL_DIR}

# copy configuration templates
case "${REDMINE_HTTPS}" in
  true)
    if [ -f "${SSL_CERTIFICATE_PATH}" -a -f "${SSL_KEY_PATH}" ]; then
      cp ${SYSCONF_TEMPLATES_DIR}/nginx/redmine-ssl /etc/nginx/sites-enabled/redmine
    else
      echo "SSL keys and certificates were not found."
      echo "Assuming that the container is running behind a HTTPS enabled load balancer."
      cp ${SYSCONF_TEMPLATES_DIR}/nginx/redmine /etc/nginx/sites-enabled/redmine
    fi
    ;;
  *) cp ${SYSCONF_TEMPLATES_DIR}/nginx/redmine /etc/nginx/sites-enabled/redmine ;;
esac
sudo -u redmine -H cp ${SYSCONF_TEMPLATES_DIR}/redmine/database.yml config/database.yml
sudo -u redmine -H cp ${SYSCONF_TEMPLATES_DIR}/redmine/unicorn.rb config/unicorn.rb
[ "${SMTP_ENABLED}" == "true" ] && \
sudo -u redmine -H cp ${SYSCONF_TEMPLATES_DIR}/redmine/smtp_settings.rb config/initializers/smtp_settings.rb

# override default configuration templates with user templates
case "${REDMINE_HTTPS}" in
  true)
    if [ -f "${SSL_CERTIFICATE_PATH}" -a -f "${SSL_KEY_PATH}" ]; then
      [ -f ${USERCONF_TEMPLATES_DIR}/nginx/redmine-ssl ]           && cp ${USERCONF_TEMPLATES_DIR}/nginx/redmine-ssl /etc/nginx/sites-enabled/redmine
    else
      [ -f ${USERCONF_TEMPLATES_DIR}/nginx/redmine ]               && cp ${USERCONF_TEMPLATES_DIR}/nginx/redmine /etc/nginx/sites-enabled/redmine
    fi
    ;;
  *) [ -f ${USERCONF_TEMPLATES_DIR}/nginx/redmine ]                && cp ${USERCONF_TEMPLATES_DIR}/nginx/redmine /etc/nginx/sites-enabled/redmine ;;
esac
[ -f ${USERCONF_TEMPLATES_DIR}/redmine/database.yml ]              && sudo -u redmine -H cp ${USERCONF_TEMPLATES_DIR}/redmine/database.yml config/database.yml
[ -f ${USERCONF_TEMPLATES_DIR}/redmine/unicorn.rb ]                && sudo -u redmine -H cp ${USERCONF_TEMPLATES_DIR}/redmine/unicorn.rb  config/unicorn.rb
[ "${SMTP_ENABLED}" == "true" ] && \
[ -f ${USERCONF_TEMPLATES_DIR}/redmine/smtp_settings.rb ]          && sudo -u redmine -H cp ${USERCONF_TEMPLATES_DIR}/redmine/smtp_settings.rb config/initializers/smtp_settings.rb
[ "${MEMCACHE_ENABLED}" == "true" ] && \
[ -f ${USERCONF_TEMPLATES_DIR}/redmine/additional_environment.rb ] && sudo -u redmine -H cp ${USERCONF_TEMPLATES_DIR}/redmine/additional_environment.rb config/additional_environment.rb

sudo -u redmine -H sed 's/{{DB_HOST}}/'"${DB_HOST}"'/' -i config/database.yml
sudo -u redmine -H sed 's/{{DB_PORT}}/'"${DB_PORT}"'/' -i config/database.yml
sudo -u redmine -H sed 's/{{DB_NAME}}/'"${DB_NAME}"'/' -i config/database.yml
sudo -u redmine -H sed 's/{{DB_USER}}/'"${DB_USER}"'/' -i config/database.yml
sudo -u redmine -H sed 's/{{DB_PASS}}/'"${DB_PASS}"'/' -i config/database.yml
sudo -u redmine -H sed 's/{{DB_POOL}}/'"${DB_POOL}"'/' -i config/database.yml

# configure secure-cookie if using SSL/TLS
if [ "${REDMINE_HTTPS}" == "true" ]; then
  sed '/^\s*config\.session_store\s/s/$/, :secure => true/' -i config/application.rb
fi

# configure nginx
sed 's/worker_processes .*/worker_processes '"${NGINX_WORKERS}"';/' -i /etc/nginx/nginx.conf
sed 's,{{INSTALL_DIR}},'"${INSTALL_DIR}"',g' -i /etc/nginx/sites-enabled/redmine
sed 's/{{REDMINE_PORT}}/'"${REDMINE_PORT}"'/' -i /etc/nginx/sites-enabled/redmine
sed 's/{{NGINX_MAX_UPLOAD_SIZE}}/'"${NGINX_MAX_UPLOAD_SIZE}"'/' -i /etc/nginx/sites-enabled/redmine
sed 's/{{NGINX_X_FORWARDED_PROTO}}/'"${NGINX_X_FORWARDED_PROTO}"'/' -i /etc/nginx/sites-enabled/redmine
sed 's,{{SSL_CERTIFICATE_PATH}},'"${SSL_CERTIFICATE_PATH}"',' -i /etc/nginx/sites-enabled/redmine
sed 's,{{SSL_KEY_PATH}},'"${SSL_KEY_PATH}"',' -i /etc/nginx/sites-enabled/redmine

# if dhparam path is valid, add to the config, otherwise remove the option
if [ -r "${SSL_DHPARAM_PATH}" ]; then
  sed 's,{{SSL_DHPARAM_PATH}},'"${SSL_DHPARAM_PATH}"',' -i /etc/nginx/sites-enabled/redmine
else
  sed '/ssl_dhparam {{SSL_DHPARAM_PATH}};/d' -i /etc/nginx/sites-enabled/redmine
fi

sed 's,{{SSL_VERIFY_CLIENT}},'"${SSL_VERIFY_CLIENT}"',' -i /etc/nginx/sites-enabled/redmine
if [ -f /usr/local/share/ca-certificates/ca.crt ]; then
  sed 's,{{CA_CERTIFICATES_PATH}},'"${CA_CERTIFICATES_PATH}"',' -i /etc/nginx/sites-enabled/redmine
else
  sed '/{{CA_CERTIFICATES_PATH}}/d' -i /etc/nginx/sites-enabled/redmine
fi

if [ "${REDMINE_HTTPS_HSTS_ENABLED}" == "true" ]; then
  sed 's/{{REDMINE_HTTPS_HSTS_MAXAGE}}/'"${REDMINE_HTTPS_HSTS_MAXAGE}"'/' -i /etc/nginx/sites-enabled/redmine
else
  sed '/{{REDMINE_HTTPS_HSTS_MAXAGE}}/d' -i /etc/nginx/sites-enabled/redmine
fi

# configure unicorn
sudo -u redmine -H sed 's,{{INSTALL_DIR}},'"${INSTALL_DIR}"',g' -i config/unicorn.rb
sudo -u redmine -H sed 's/{{UNICORN_WORKERS}}/'"${UNICORN_WORKERS}"'/' -i config/unicorn.rb
sudo -u redmine -H sed 's/{{UNICORN_TIMEOUT}}/'"${UNICORN_TIMEOUT}"'/' -i config/unicorn.rb

# configure relative_url_root
if [ -n "${REDMINE_RELATIVE_URL_ROOT}" ]; then
  sudo -u redmine -H cp -f ${SYSCONF_TEMPLATES_DIR}/redmine/config.ru config.ru
  sudo -u redmine -H sed 's,{{REDMINE_RELATIVE_URL_ROOT}},'"${REDMINE_RELATIVE_URL_ROOT}"',' -i config/unicorn.rb
  sed 's,# alias '"${INSTALL_DIR}"'/public,alias '"${INSTALL_DIR}"'/public,' -i /etc/nginx/sites-enabled/redmine
  sed 's,{{REDMINE_RELATIVE_URL_ROOT}},'"${REDMINE_RELATIVE_URL_ROOT}"',' -i /etc/nginx/sites-enabled/redmine
else
  sudo -u redmine -H sed '/{{REDMINE_RELATIVE_URL_ROOT}}/d' -i config/unicorn.rb
  sed 's,{{REDMINE_RELATIVE_URL_ROOT}},/,' -i /etc/nginx/sites-enabled/redmine
fi

# disable ipv6 support
if [ ! -f /proc/net/if_inet6 ]; then
  sed -e '/listen \[::\]:80/ s/^#*/#/' -i /etc/nginx/sites-enabled/redmine
  sed -e '/listen \[::\]:443/ s/^#*/#/' -i /etc/nginx/sites-enabled/redmine
fi

if [ "${SMTP_ENABLED}" == "true" ]; then
  # configure mail delivery
  sudo -u redmine -H sed 's/{{SMTP_METHOD}}/'"${SMTP_METHOD}"'/g' -i config/initializers/smtp_settings.rb
  sudo -u redmine -H sed 's/{{SMTP_HOST}}/'"${SMTP_HOST}"'/' -i config/initializers/smtp_settings.rb
  sudo -u redmine -H sed 's/{{SMTP_PORT}}/'"${SMTP_PORT}"'/' -i config/initializers/smtp_settings.rb

  case "${SMTP_USER}" in
    "") sudo -u redmine -H sed '/{{SMTP_USER}}/d' -i config/initializers/smtp_settings.rb ;;
    *) sudo -u redmine -H sed 's/{{SMTP_USER}}/'"${SMTP_USER}"'/' -i config/initializers/smtp_settings.rb ;;
  esac

  case "${SMTP_PASS}" in
    "") sudo -u redmine -H sed '/{{SMTP_PASS}}/d' -i config/initializers/smtp_settings.rb ;;
    *) sudo -u redmine -H sed 's/{{SMTP_PASS}}/'"${SMTP_PASS}"'/' -i config/initializers/smtp_settings.rb ;;
  esac

  sudo -u redmine -H sed 's/{{SMTP_DOMAIN}}/'"${SMTP_DOMAIN}"'/' -i config/initializers/smtp_settings.rb
  sudo -u redmine -H sed 's/{{SMTP_STARTTLS}}/'"${SMTP_STARTTLS}"'/' -i config/initializers/smtp_settings.rb

  if [ -n "${SMTP_OPENSSL_VERIFY_MODE}" ]; then
    sudo -u redmine -H sed 's/{{SMTP_OPENSSL_VERIFY_MODE}}/'"${SMTP_OPENSSL_VERIFY_MODE}"'/' -i config/initializers/smtp_settings.rb
  else
    sudo -u redmine -H sed '/{{SMTP_OPENSSL_VERIFY_MODE}}/d' -i config/initializers/smtp_settings.rb
  fi

  case "${SMTP_AUTHENTICATION}" in
    "") sudo -u redmine -H sed '/{{SMTP_AUTHENTICATION}}/d' -i config/initializers/smtp_settings.rb ;;
    *) sudo -u redmine -H sed 's/{{SMTP_AUTHENTICATION}}/'"${SMTP_AUTHENTICATION}"'/' -i config/initializers/smtp_settings.rb ;;
  esac

fi

# create file uploads directory
mkdir -p ${DATA_DIR}/files
chmod 755 ${DATA_DIR}/files
chown redmine:redmine ${DATA_DIR}/files

# symlink file store
rm -rf files
if [ -d /redmine/files ]; then
  # for backward compatibility, user should mount the volume at ${DATA_DIR}
  echo "WARNING: "
  echo "  The data volume path has now been changed to ${DATA_DIR}/files."
  echo "  Refer http://git.io/H59-lg for migration information."
  echo "  Setting up backward compatibility..."
  chmod 755 /redmine/files
  chown redmine:redmine /redmine/files
  ln -sf /redmine/files
else
  ln -sf ${DATA_DIR}/files
fi

# due to the nature of docker and its use cases, we allow some time
# for the database server to come online.

prog=$(find /usr/lib/postgresql/ -name pg_isready)
prog="${prog} -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME} -t 1"
timeout=60
echo -n "Waiting for database server to accept connections"
while ! ${prog} >/dev/null 2>&1
do
  timeout=$(expr $timeout - 1)
  if [ $timeout -eq 0 ]; then
    echo -e "\nCould not connect to database server. Aborting..."
    exit 1
  fi
  echo -n "."
  sleep 1
done
echo

# migrate database if the redmine version has changed.
CURRENT_VERSION=
REDMINE_VERSION=$(cat ${INSTALL_DIR}/VERSION)
[ -f ${DATA_DIR}/tmp/VERSION ] && CURRENT_VERSION=$(cat ${DATA_DIR}/tmp/VERSION)
if [ "${REDMINE_VERSION}" != "${CURRENT_VERSION}" ]; then
  # recreate the tmp directory
  rm -rf ${DATA_DIR}/tmp
  sudo -u redmine -H mkdir -p ${DATA_DIR}/tmp/
  chmod -R u+rwX ${DATA_DIR}/tmp/

  # create the tmp/thumbnails directory
  sudo -u redmine -H mkdir -p ${DATA_DIR}/tmp/thumbnails

  # create the plugin_assets directory
  sudo -u redmine -H mkdir -p ${DATA_DIR}/tmp/plugin_assets

  # copy the installed gems to tmp/bundle and move the Gemfile.lock
  sudo -u redmine -H cp -a vendor/bundle ${DATA_DIR}/tmp/
  sudo -u redmine -H cp -a Gemfile.lock ${DATA_DIR}/tmp/

  echo "Migrating database. Please be patient, this could take a while..."
  # Database created on PostgreSQL setup
  # sudo -u redmine -H bundle exec rake db:create RAILS_ENV=production
  sudo -u redmine -H bundle exec rake db:migrate RAILS_ENV=production

  # Adding default configiration
  [ ! -f ${DATA_DIR}/tmp/VERSION ] && \
    sudo -u redmine -H RAILS_ENV=production REDMINE_LANG=ru bundle exec rake redmine:load_default_data

  # clear sessions and application cache
  sudo -u redmine -H bundle exec rake tmp:cache:clear RAILS_ENV=production >/dev/null
  sudo -u redmine -H bundle exec rake tmp:sessions:clear RAILS_ENV=production >/dev/null

  echo "Generating secure token..."
  sudo -u redmine -H bundle exec rake generate_secret_token RAILS_ENV=production >/dev/null

  # update version file
  echo "${REDMINE_VERSION}" | sudo -u redmine -H tee --append ${DATA_DIR}/tmp/VERSION >/dev/null
fi

# create a cronjob to periodically fetch commits
case "${REDMINE_FETCH_COMMITS}" in
  hourly|daily|monthly)
    crontab -u redmine -l >/tmp/cron.redmine
    if ! grep -q 'Repository.fetch_changesets' /tmp/cron.redmine; then
      # echo "@${REDMINE_FETCH_COMMITS} cd /home/redmine/redmine && ./bin/rails runner \"Repository.fetch_changesets\" -e production >> log/cron_rake.log 2>&1" >>/tmp/cron.redmine
      echo "@${REDMINE_FETCH_COMMITS} cd /home/redmine/redmine && ./script/rails runner \"Repository.fetch_changesets\" -e production >> log/cron_rake.log 2>&1" >>/tmp/cron.redmine
      crontab -u redmine /tmp/cron.redmine
    fi
    rm -rf /tmp/cron.redmine
    ;;
esac

# remove vendor/bundle and symlink to ${DATA_DIR}/tmp/bundle
rm -rf vendor/bundle Gemfile.lock
ln -sf ${DATA_DIR}/tmp/bundle vendor/bundle
ln -sf ${DATA_DIR}/tmp/Gemfile.lock Gemfile.lock

# install user plugins
if [ -d ${DATA_DIR}/plugins ]; then

  echo "Installing plugins..."
  sed -i -r 's/^\s\send$/  config.active_record.whitelist_attributes = false\n\0/' config/application.rb
  
  rsync -avq --chown=redmine:redmine ${DATA_DIR}/plugins/ ${INSTALL_DIR}/plugins/
  # install gems and migrate the plugins when plugins are added/removed
  CURRENT_SHA1=
  [ -f ${DATA_DIR}/tmp/plugins.sha1 ] && CURRENT_SHA1=$(cat ${DATA_DIR}/tmp/plugins.sha1)
  PLUGINS_SHA1=$(find ${DATA_DIR}/plugins -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum | awk '{print $1}')
  if [ "${CURRENT_SHA1}" != "${PLUGINS_SHA1}" ]; then
    # remove the existing plugin assets
    # this ensures there is no cruft when a plugin is removed.
    rm -rf ${DATA_DIR}/tmp/plugin_assets/*

    echo "Installing gems required by plugins..."
    bundle install --without development tests --path vendor/bundle

    echo "Migrating plugins. Please be patient, this could take a while..."
    sudo -u redmine -H bundle exec rake redmine:plugins:migrate RAILS_ENV=production

    # save SHA1
    echo -n "${PLUGINS_SHA1}" > ${DATA_DIR}/tmp/plugins.sha1
  fi

  # source plugins init script
  if [ -f ${DATA_DIR}/plugins/init ]; then
    echo "Executing plugins startup script..."
    . ${DATA_DIR}/plugins/init
  fi
  
  # sed -i '/config.active_record.whitelist_attributes = false$/d' config/application.rb
fi

# install user themes
if [ -d ${DATA_DIR}/themes ]; then
  echo "Installing themes..."
  rsync -avq --chown=redmine:redmine ${DATA_DIR}/themes/ ${INSTALL_DIR}/public/themes/
fi

appStart () {
  # remove stale unicorn pid if it exists.
  rm -rf tmp/pids/unicorn.pid

  # remove state unicorn socket if it exists
  rm -rf tmp/sockets/redmine.socket

  # start supervisord
  exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
}

appRake () {
  if [ -z ${1} ]; then
    echo "Please specify the rake task to execute. See http://www.redmine.org/projects/redmine/wiki/RedmineRake"
    return 1
  fi
  echo "Running redmine rake task..."
  sudo -u redmine -H bundle exec rake $@ RAILS_ENV=production
}

appHelp () {
  echo "Available options:"
  echo " app:start          - Starts the redmine server (default)"
  echo " app:rake <task>    - Execute a rake task."
  echo " app:help           - Displays the help"
  echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
  app:start)
    appStart
    ;;
  app:rake)
    shift 1
    appRake $@
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
